### ISSUE TITLE
Update to v7.6.2

### ISSUE THREAD

**Issue by ivmai** [andyli/libgc-cygwin#1]
Hi Andy,

Could you please update libgc.cygport to 7.6.2 and ask Cygwin guys to update the package?

Some notes:
1. PATCH_URI should be removed as https://github.com/ivmai/bdwgc/pull/161 is merged
2. It would be good to add "--enable-handle-fork" to CYGCONF_ARGS

Thank you

**Comment by andyli** [comment]
Just updated, but not yet upload.
There was an error when I run the tests:
```
================================
   gc 7.6.2: ./test-suite.log
================================

# TOTAL: 15
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_cpp
==============

usage: test_cpp number-of-iterations
Assuming 10 iters
Starting iteration 1
FAIL test_cpp.exe (exit status: 134)

```

Do you have any idea?

**Comment by andyli** [comment]
Just did a `git bisect` and it said https://github.com/ivmai/bdwgc/commit/20bf475a21e863eb127a6230d729d42c4bab74bc is the first bad commit.

**Comment by ivmai** [comment]
Thank you for doing bisect but virtual destructor is not the root cause - test_cpp calls wrong delete operator for a. I've created the ticket (https://github.com/ivmai/bdwgc/issues/195). I haven't found the solution yet, I'm adding the test case now.

**Comment by andyli** [comment]
Thanks for looking into it so quickly. Do you think it is a regression (between 7.6.0 and 7.6.2)? If not, I will just upload 7.6.2 as is.

**Comment by ivmai** [comment]
I haven't checked it yet. No hurry. I think it is better to fix (if not difficult) before the release.
I will look into it next week.

**Comment by ivmai** [comment]
I found the solution, testing it now.

**Comment by ivmai** [comment]
https://github.com/ivmai/bdwgc/commit/3150107d3e12b06764e3fd4598cef0652e127b3c should fix the issue.

**Comment by andyli** [comment]
I confirm the tests passed now. I've uploaded 7.6.2 with the fix applied as a patch. Thanks!

**Comment by fdopen** [comment]
Did you update the dependencies as well?
guile and other packages are linked against `cyggc-1.dll`, while your new packages ships `cyggc-2.dll`.
Therefore make and similar tools currently won't work, unless you downgrade libgc manually.
(I didn't check, if it is just a problem with my mirror. Perhaps it's already resolved).

**Comment by andyli** [comment]
Ah... good catch. My bad. I am asking for the cygwin devs' help to remove the new version (or find a way to fix it).

**Comment by ivmai** [comment]
While downgrade libgc manually is a potential solution, please do not do it (otherwise it would be necessary to perform manual downgrade on every libgc release).
I'm sorry about changing API version but at some moment some API GC_set_* functions were changed in a binary-incompatible way.

BTW. How to find all the dependent packages?

**Comment by ivmai** [comment]
Ah, we seem to break many packages. :( I can't even run "make" after upgrading libgc to 7.6.2 on my PC (using Cygwin setup). As a workaround I have installed libgc 7.2d.

Urgent actions of Cygwin maintainers are needed to delete the current libgc 7.6.2 (and restore 7.6.0).

**Comment by andyli** [comment]
I've just removed the faulty 7.6.2 packages for now, and will look into updating it properly: https://cygwin.com/ml/cygwin-apps/2018-01/msg00050.html

**Comment by ivmai** [comment]
Great!

Now the questions are:
* how to find all Cygwin packages depending on libgc
* how to update version in the dependent packages atomically (together with the gc 7.6.2 release).

**Comment by andyli** [comment]
I have found a way that doesn't require dependent packages to rebuild.
I created a new 7.6.0-2 package that splits libgc1 into libgc1 libgccpp1 libcord1, and then let libgc1 requires the split out packages (libgccpp1 libcord1), such that requiring libgc1 will get all the 3 dll files anyway.
The 7.6.2 package builds libgc2 libgccpp1 libcord1. The libgc2 package does not have the extra requires on libgccpp1 libcord1. It will be fine since future packages that builds against 7.6.2 will automatically depends the other packages if needed.
In this way, libgc1 and libgc2 can co-exist in a system.
Let me know if I missed anything.

**Comment by ivmai** [comment]
I wonder what can I do in the upstream? The version change affects many downstream packages. It is not correct to decrement "current" part of the version, but what about increment of "age"?

**Comment by andyli** [comment]
I'm not sure if I understand. I don't think there is any problem right now. e.g. libneko2 was built with gc 7.6.0 (i.e. depends on libgc1 package, which provides cyggc-1.dll). It will continue to work despite there is a libgc2 package from gc 7.6.2 now.

Previously I wrongly put cyggc-2.dll into a new version of the libgc1 package, but since it's removed, it will no longer affect users. New installation of libgc1 will get the good old version that provides cyggc-1.dll.

As long as the SO version number is reliable, i.e. newer cyggc-N.dll is compatible with older cyggc-N.dll for all N, it will be fine.

BTW, turn out there aren't many packages in cygwin that directly depends on libgc. The direct dependents are:

```
$ cygcheck-dep -S -n libgc1
 libgc1: is needed for ( inkscape libgc libgc-devel libguile2.0_22 libneko2 w3m )
```

**Comment by ivmai** [comment]
>  It will continue to work despite there is a libgc2 package from gc 7.6.2 now.

Not everything will work correctly: e.g. libcord1 now depends on libgc2, so if an app depends on libgc1 and libcord1 then it will crash most likely.

**Comment by ivmai** [comment]
I'm thinking about making a new upstream release (v7.6.4) with libtool version changed to 5:0:4.

**Comment by ivmai** [comment]
> I've uploaded 7.6.2 with the fix applied as a patch.

In v7.6.4, the patch is not needed.

**Comment by ivmai** [comment]
I suggest the following modification of your cygport file (I have not tried it though):

```diff
diff --git a/libgc.cygport b/libgc.cygport
index 2ad70b0..b8d3abf 100644
--- a/libgc.cygport
+++ b/libgc.cygport
@@ -1,6 +1,6 @@
 NAME="libgc"
-VERSION=7.6.2
-RELEASE=2
+VERSION=7.6.4
+RELEASE=1
 CATEGORY="Libs"
 SUMMARY="Boehm-Demers-Weiser garbage collector library"
 DESCRIPTION="The Boehm-Demers-Weiser conservative garbage collector can be
@@ -10,22 +10,18 @@ explicitly deallocating memory that is no longer useful. The collector
 automatically recycles memory when it determines that it can no longer
 be otherwise accessed."
 HOMEPAGE="http://www.hboehm.info/gc"
-SRC_URI="${HOMEPAGE}/gc_source/gc-${VERSION}.tar.gz"
+SRC_URI="https://github.com/ivmai/bdwgc/releases/download/v${VERSION}/gc-${VERSION}.tar.gz"
 SRC_DIR="gc-${VERSION}"
 
-# https://github.com/andyli/libgc-cygwin/issues/1
-PATCH_URI="https://github.com/ivmai/bdwgc/commit/3150107d3e12b06764e3fd4598cef0652e127b3c.patch"
-
 DEPEND="pkgconfig(atomic_ops)"
 
-PKG_NAMES="libgc2 libgccpp1 libcord1 libgc-devel"
+PKG_NAMES="libgc1 libgc-devel"
 
 libgc_devel_OBSOLETES="libgc"
 
-libgc2_CONTENTS="usr/bin/cyggc-2.dll"
-libgccpp1_CONTENTS="usr/bin/cyggccpp-1.dll"
-libcord1_CONTENTS="usr/bin/cygcord-1.dll"
-
+libgc1_CONTENTS="
+    usr/bin/*-1.dll
+"
 libgc_devel_CONTENTS="
     usr/include/
     usr/lib/
```

**Comment by andyli** [comment]
Thanks for the patch, I think I will keep the dll files in separated packages as it is done in most packages I know (e.g. [mbedtls on Debian](https://packages.debian.org/source/sid/mbedtls)). I guess it is a better practice since the downstream package can define which exactly dll they depend on. What do you think?

**Comment by ivmai** [comment]
I don't have any firm opinion about it. I think it is OK to have separated packages.

**Comment by andyli** [comment]
I've uploaded the update on Tuesday and it seems to be good.

**Comment by ivmai** [comment]
Thank you.

But I have a question: if we have separate packages, why libgc1 depends on libgccpp1 and libcord1? It should not.

**Comment by ivmai** [comment]
And it would be good to remove libgc2 package (to avoid confusion that libgc1 is newer than libgc1)

**Comment by andyli** [comment]
> why libgc1 depends on libgccpp1 and libcord1? It should not.

[libgc1-7.6.0-2](http://mirror.pkill.info/cygwin/x86_64/release/libgc/libgc1/libgc1-7.6.0-2.hint) depends on those for backward compatibility - installing it will obtain all 3 dll files as before the split.
The latest package, [libgc1-7.6.4-1](http://mirror.pkill.info/cygwin/x86_64/release/libgc/libgc1/libgc1-7.6.4-1.hint), doesn't depends on those.
I noticed the cygwin setup exe is a bit confused, but it should be fine once the older packages phased out. Cygwin keeps only the last 3 versions of a package.

> remove libgc2

I suggest keeping libgc2 because 7.6.2 was made available for some time, so people may have used it to build binaries, and they should still be able to get libgc2. It shouldn't cause any harm since people will use the latest devel package for development. libgc2 wouldn't satisfy a dependency on libgc1 no matter libgc2 is newer or not.

**Comment by ivmai** [comment]
Hmm. I have removed libgc1, libgc2, libcord, libgccpp and all dependent packages. Then I tried to install libgc1-7.6.4-1 only, Cygwin (both x86 and x86_64) reported me:
```
libcord1	(7.6.4-1)
	Boehm-Demers-Weiser garbage collector library
	Required by: libgc1

libgc2	(7.6.2-2)
	Boehm-Demers-Weiser garbage collector library
	Required by: libcord1, libgccpp1

libgccpp1	(7.6.4-1)
	Boehm-Demers-Weiser garbage collector library
	Required by: libgc1
```

Should I just wait "once the older packages phased out"?

About removing libgc2. I don't quite agree that it should be kept because someone already uses it (I think if something occasionally depends on libgc2 then the former should be rebuilt). Could we at least deprecate it (in favor of libgc1)?

**Comment by andyli** [comment]
> Should I just wait "once the older packages phased out"?

I've just tested the [cygwin setup 2.887 release candidate](https://cygwin.com/ml/cygwin/2018-02/msg00062.html), which replaced its dependency resolver. I'm able to install just libgc1 without libgc2. Note that [libguile2.0_22-2.0.14-2](http://mirror.pkill.info/cygwin/x86_64/release/guile/libguile2.0_22/libguile2.0_22-2.0.14-2.hint) was unfortunately built with libgc2 already, but I'm able to downgrade it to [libguile2.0_22-2.0.14-1](http://mirror.pkill.info/cygwin/x86_64/release/guile/libguile2.0_22/libguile2.0_22-2.0.14-1.hint) to avoid getting libgc2.
I guess the new setup will come sooner than the older packages phased out.

> Could we at least deprecate it (in favor of libgc1)?

I can add a warning in libgc2's description. Is that what you want?

**Comment by ivmai** [comment]
> I can add a warning in libgc2's description. Is that what you want?

I mean adding a line like (maybe I'm wrong):
libgc1_OBSOLETES="libgc2"

**Comment by andyli** [comment]
OBSOLETES will create an empty libgc2 package that depends on libgc1. In
this case there will be no actual libgc2 dll file installed.
It is only useful for renaming packages.

**Comment by ivmai** [comment]
I see. Then a warning in libgc2's description would be OK.
Thank you for the explanation.
